// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqYsLyeZ1pJ4D2sdCRx5q_iQyhmVNssD0',
    appId: '1:300330514648:web:76cdd225115ca9d71f7fad',
    messagingSenderId: '300330514648',
    projectId: 'mad1-a22f9',
    authDomain: 'mad1-a22f9.firebaseapp.com',
    storageBucket: 'mad1-a22f9.appspot.com',
    measurementId: 'G-X7YR21HCC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_k-F1iehWaakzDPYzK34RxrrxH8dzE_I',
    appId: '1:300330514648:android:d791bd8031ec3c2c1f7fad',
    messagingSenderId: '300330514648',
    projectId: 'mad1-a22f9',
    storageBucket: 'mad1-a22f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7YCh2zbtcOScG8MBWr7h-3oX7zWxh5JI',
    appId: '1:300330514648:ios:70a76d665e409c751f7fad',
    messagingSenderId: '300330514648',
    projectId: 'mad1-a22f9',
    storageBucket: 'mad1-a22f9.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7YCh2zbtcOScG8MBWr7h-3oX7zWxh5JI',
    appId: '1:300330514648:ios:70a76d665e409c751f7fad',
    messagingSenderId: '300330514648',
    projectId: 'mad1-a22f9',
    storageBucket: 'mad1-a22f9.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqYsLyeZ1pJ4D2sdCRx5q_iQyhmVNssD0',
    appId: '1:300330514648:web:b0867065e582054b1f7fad',
    messagingSenderId: '300330514648',
    projectId: 'mad1-a22f9',
    authDomain: 'mad1-a22f9.firebaseapp.com',
    storageBucket: 'mad1-a22f9.appspot.com',
    measurementId: 'G-RGT2P011MN',
  );
}
